### PR TITLE
add sequence doc for 0.8

### PR DESCRIPTION
**Pull request by lacrimosaprinz**
## What type of PR is this?

- [ ] Enhancement
- [ ] Displaying
- [ ] Typo
- [x] Doc Request

## Which issue(s) this PR fixes:

issue #
https://github.com/matrixorigin/matrixone/issues/6590

### CODE REVIEW

**Review by dengn — CHANGES_REQUESTED** [review]
please refer to comments in https://github.com/matrixorigin/matrixorigin.io.cn/pull/297

**Review by dengn — CHANGES_REQUESTED** [review]
Need to mention that: auto_increment and sequence cannot be used together
mysql> create table abc(a int auto_increment default nextval('seq_id'), b int);
ERROR 20301 (HY000): invalid input: invalid default value for 'a'

**Comment by lacrimosaprinz** [comment]
fixed

**Review by domingozhang — APPROVED** [review]

**Comment by dengn** [comment]
Fix lint

**Review by iceTTTT — APPROVED** [review]

**Review by dengn — APPROVED** [review]

**Pull request merged**
